version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-cobudget:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-cobudget: