spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  show-actuator: true
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
      scopes: openid