server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

logging:
  level:
    org.springframework.jdbc.core: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  cors:
    origins: "http://localhost:3000"
okta:
  oauth2:
    issuer: "https://dev-01647397.okta.com/oauth2/default"
