server:
  port: ${APP_PORT}

okta:
  oauth2:
    issuer: ${OAUTH_ISSUER}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
security:
  cors:
    origins: ${CORS_ORIGINS}
