server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ""
    username: ""
    password: ""
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://idp.example.com/issuer"

security:
  cors:
    origins: ""

cobudget:
  receipts:
    bucket: test
