server:
  port: ${APP_PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER}

security:
  cors:
    origins: ${CORS_ORIGINS}

cobudget:
  receipts:
    bucket: cobudget-eu-central-1-receipts
