spring:
  profiles:
    active: prod

springdoc:
  show-actuator: true
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
      scopes: openid
server:
  forward-headers-strategy: framework