server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ""
    username: ""
    password: ""
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ""

security:
  cors:
    origins: ""
