server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://dev-01647397.okta.com/oauth2/default"

logging:
  level:
    org.springframework.jdbc.core: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  cors:
    origins: "http://localhost:3000"

cobudget:
  receipts:
    bucket: cobudget-eu-central-1-receipts

springdoc:
  show-actuator: true
  swagger-ui:
    oauth:
      client-id: 0oa24pfnd1D6oI3Ak5d7