name: Add assigned issue to Todoist

on:
  issues:
    types: [ assigned ]

jobs:
  add-task:
    if: github.event.assignee.login == 'dawids21'
    name: Add task
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.todoist.com/rest/v2/tasks'
          method: 'POST'
          bearerToken: ${{ secrets.TODOIST_API_TOKEN }}
          escapeData: true
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "content": "${{ github.event.issue.title }}",
              "labels": ["CoBudget"],
              "description": "${{ github.event.issue.body }}"
            }
