name: Add assigned issue to Todoist

on:
  issues:
    types: [ assigned ]

jobs:
  add-task:
    name: Add task
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"